#!/bin/bash

# dépendancies : enscript, ps2pdf
# comments :
# It converts a text to postscript and postcript to pdf
# Simple and probably useful.

if [ $# -ne 2 ]
then
clear
echo -e "syntax error\n\n"$0" <fichier.txt> <output.pdf>"
fi

if [ $# -eq 2 ]
then
clear
enscript $1 -o - | ps2pdf - $2
fi
